### ISSUE TITLE
Support LLVM 9.0

### ISSUE THREAD

**Issue by XVilka** [staticafi/symbiotic#119]
LLVM 9.0 was recently released, with [many things inside](http://releases.llvm.org/9.0.0/docs/ReleaseNotes.html):
- The RISCV target is no longer “experimental” (see Changes to the RISCV Target below for more details).
- Support for target-independent hardware loops in IR has been added, with PowerPC and Arm implementations.
- Various optimisations

Changes to the LLVM IR

  -  Added `immarg` parameter attribute. This indicates an intrinsic parameter is required to be a simple constant. This annotation must be accurate to avoid possible miscompiles.
 -   The 2-field form of global variables `@llvm.global_ctors` and `@llvm.global_dtors` has been deleted. The third field of their element type is now mandatory. Specify i8* null to migrate from the obsoleted 2-field form.
 -   The `byval` attribute can now take a type parameter: `byval(<ty>)`. If present it must be identical to the argument’s pointee type. In the next release we intend to make this parameter mandatory in preparation for opaque pointer types.
 -   `atomicrmw xchg` now allows floating point types
 -   `atomicrmw` now supports `fadd` and `fsub`

Depends on https://github.com/klee/klee/issues/1136

**Comment by mchalupa** [comment]
Modules with LLVM 9.0 support:
- [x] dg
- [x] sbt-slicer
- [ ] sbt-instrumentation
- [ ] llvm2c
- [ ] sbt transformations
- [ ] KLEE

**Comment by kdudka** [comment]
@mchalupa I was told that the llvm2c component is optional.  Is it possible to build symbiotic with some basic configuration on Fedora 31+ against system llvm-9.0?

**Comment by mchalupa** [comment]
Symbiotic should now have the LLVM 9.0 support. (I tested also system-build.sh on Fedora31 and it worked).

**Comment by kdudka** [comment]
Yes, 8738e5b9a1ff05e66a0facb17d9a57165c6ad3bc builds successfully on f30+:

https://copr.fedorainfracloud.org/coprs/acalabek/symbiotic/build/1129971/

Thank you for fixing it!
