### ISSUE TITLE
False negative when calling free on a stack variable

### ISSUE THREAD

**Issue by imartisko** [staticafi/symbiotic#123]
```
#include<stdlib.h>
int main (int argc, char** argv)
{
    int a;
    free(&a);
}
```

The code above does not trigger an error (neither with `--prp=memsafety` nor with `--prp=undefined`).

**Comment by mchalupa** [comment]
It's probably a bug in PTA in instrumentation, because no instruction was marked as possibly dangerous:

```
Info: Number of inserted calls:
Info:   0 of __INSTR_mark_free (blocked 3)
```
