### ISSUE TITLE
Conditional malloc not detected consistently

### ISSUE THREAD

**Issue by imartisko** [staticafi/symbiotic#124]
```
#include<stdlib.h>
int main (int argc, char** argv)
{
  int *a;
  int b = 0;
  //if (0 > 0)
  if (b > 0)
  {
    a = malloc(sizeof(int));
  }
  *a = 42;
  free(a);
}
```
`symbiotic --prp=memsafety ` with the code above returns different results based on which version of `if(...)` is used. When using the (0>0) version, the error is detected; when using the (b>0), it is not.

`symbiotic --version` is 6.1.0-dev

**Comment by mchalupa** [comment]
Looks working in the devel version of Symbiotic.

**Comment by mchalupa** [comment]
The changes from devel were merged to master. Can I close the issue?

**Comment by kdudka** [comment]
8738e5b9a1ff05e66a0facb17d9a57165c6ad3bc works as expected on the above test in my testing environment.  Thanks for the fix!

@imartisko We should include the  test in our benchmark.

**Comment by mchalupa** [comment]
btw. can I use the code as a test in Symbiotic?

**Comment by kdudka** [comment]
Sure!
