### ISSUE TITLE
memsafety: Undetected invalid free of addresses pointing to data or bss sections

### ISSUE THREAD

**Issue by lzaoral** [staticafi/symbiotic#135]
Hi,
Symbiotic fails to find violations in following C programs (even though the underlying instance of KLEE informs about the error) with the `memsafety` property:

```c
#include <stdlib.h>

int a = 5;
int main(void) { free(&a); }
```
```c
#include <stdlib.h>

int a[10];
int main(void) { free(a); }
```
Build used: https://copr.fedorainfracloud.org/coprs/jamartis/symbiotic/build/1220239/

**Comment by mchalupa** [comment]
Thanks for reporting this, should be fixed in master now.
