### ISSUE TITLE
The null-deref property is missing

### ISSUE THREAD

**Issue by lzaoral** [staticafi/symbiotic#139]
Hi,
the usage message mentions the `null-deref` property, but Symbiotic fails to recognise it:

```shell
$ symbiotic --prp=null-deref test.c                                                         
7.0.0-dev-llvm-9.0.1-symbiotic:44b91251-dg:e89761ff-sbt-slicer:fff6245c-sbt-instrumentation:2db331fb-klee:59f3e288                                                                            
ERROR: Could not derive the right property
```

**Comment by mchalupa** [comment]
Yes, we haven't maintained this property for quite some time. We should either remove it from the message or fix it. Do you need it promptly?

**Comment by kdudka** [comment]
I do not think we need `null-deref` specifically.  If `NULL` dereferences are already checked with `--prp=memsafety`, it will work for us.

**Comment by mchalupa** [comment]
Yes, `NULL` dereferences are checked with `--prp=memsafety`, however, there are cases (at least for us), where we would like to check only for null-dereferences, so I fixed this property instead of removing the message.

**Comment by kdudka** [comment]
Thanks!
