### ISSUE TITLE
Incorrect answers in DeviceDrivers-ReachSafety

### ISSUE THREAD

**Issue by tomsik68** [staticafi/symbiotic#174]
In the following two benchmarks, we answer `false(unreach-call)`. According to sv-benchmarks repo, the correct answer is `true`. I tried to disable slicing, but it has no effect on it. Even klee error path replay confirms the violation. CPAchecker witness checker is unable to confirm the violation. Since debugging this is painful, I don't consider fixing this a high priority.

http://arran.fi.muni.cz:3000/files?&incorrect=on&run=591&run=590&benchmarks=64&filter=false

**Comment by tomsik68** [comment]
Pass `-prepare` deletes body of `ldv_is_err`. As a result, nondet value is assigned to the function's return value.  `ldv_is_err(ptr)` is defined as `ptr > 18446744073709547521UL`. When `ldv_is_err(0)` should also return `0`, but klee assigns it `1` because it is extern at that point. This leads to assertion violation, but I believe the path is infeasible because `ptr == 0 && ptr > 18446744073709547521UL` is infeasible.

This problem occurs in `m0_drivers-usb-gadget-g_printer-ko--106_1a--2b9ec6c-1.yml`.

Implementing pointer comparison in klee should help us avoid this problem, since klee will be able to interpret `ldv_is_err` and we won't have to remove it.

**Comment by mchalupa** [comment]
Good catch! Will you provide a patch or should I do that?

**Comment by tomsik68** [comment]
I'd like to help, but I'm not sure how to implement it.

**Comment by mchalupa** [comment]
We still need to test it on a bigger scale. If the patch does not work as expected, we re-open (or open a new) issue.
