### ISSUE TITLE
Termination of benchmarks with assertions

### ISSUE THREAD

**Issue by tomsik68** [staticafi/symbiotic#178]
When we check for termination, we use `assert` as a marker of infinite loop. Some benchmarks in termination have reachable assert and Symbiotic considers them non-terminating.

From my understanding, we first replace `__assert_fail` by `__VERIFIER_assume(0)` and then replace `__VERIFIER_assume(x)` by `__INSTR_check_assume(x)`. In the end, this calls `__INSTR_fail` which reports an infinite loop.

The problem appears in this benchmark: https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ldv-regression/1_3.i .

I suggest using `-remove-errors-use-exit` as it doesn't insert an assertion and preserves termination. It works on the benchmark above.

**Comment by mchalupa** [comment]
Yes, the problematic part is to run `-remove-error-calls` pass right after the compilation. Weird, it worked the last year and I do not remember changing any bit of it...
