### ISSUE TITLE
VR plugin does not handle a simple benchmark

### ISSUE THREAD

**Issue by mchalupa** [staticafi/symbiotic#182]
I assume that the value relations analysis plugin should decide this but it does not (but maybe it's too late in the night and I overlooked something...)
https://github.com/sosy-lab/sv-benchmarks/blob/master/c/termination-crafted/Arrays01-EquivalentConstantIndices-1.c

@GiraffeReversed , can you take a look?

**Comment by GiraffeReversed** [comment]
Hm, I tried it and it worked as expected (marked all accesses true) in my feature branch, which nevertheless contains some extra commits. Unfortunately, I do not have much time to look into it today, only tomorrow.

**Comment by GiraffeReversed** [comment]
Well, for a significant part of today I have been trying to reproduce the failure to validate, but I could not repreduce it. I was not able to try it in Symbiotic itself (problems with build still, sorry).
I did try the following setup -- I used dg in practically the same version as is in your master right now and I added a file I use to test the analysis, which simluates the ValueRelationsPlugin (it has exactly the same contents, except I do not have to compile it as a part of instrumentation, but I include it right into llvm-vr-dump and I print the results of attempted validations of pointers obtained from the gep instruction). In that setup, I was able to validate all four accesses done in the benchmark.

**Comment by GiraffeReversed** [comment]
I have just tried verifying the benchmark and I was able to mark it correct with both master and svcomp21-v1 version of symbiotic. Specifically for master version, I used commits
```
8.0.0-pre-llvm-10.0.1-symbiotic:d52fe5c6-dg:c04e6dd4-sbt-slicer:319209dd-sbt-instrumentation:ad1d134f-klee:18262515
```
for symbiotic and its components, `99d37c5b` version of sv-benchmarks and the command 
```
./scripts/symbiotic --prp=memsafety ../sv-benchmarks/c/termination-crafted/Arrays01-EquivalentConstantIndices-1.c
```

**Comment by mchalupa** [comment]
Then let's make this a history. We can re-open if needed.
