### ISSUE TITLE
Build exits with KLEE needs 32-bit headers to build

### ISSUE THREAD

**Issue by tkratochvila** [staticafi/symbiotic#186]
When building **symbiotic** on CentoOS using **build.sh**, the build exits with:
> KLEE needs 32-bit headers to build 
> 32-bit versions of runtime libraries

I would be helpful to make it more specific.

**Comment by kdudka** [comment]
I would suggest to install `glibc-devel.i686`, assuming it runs on Intel.

**Comment by tkratochvila** [comment]
Thanks @kdudka for the correct solution. The same suggested @mchalupa and asked me to report this issue.
The **build.sh** should clearly state, which 32-bit headers KLEE needs.
