### ISSUE TITLE
symbiotic build - git_submodule_init() doesn't copy submodules to the build directory

### ISSUE THREAD

**Issue by rtrembecky** [staticafi/symbiotic#47]
directories LLVMSlicer, dg and svc15 are not created during build, build is aborted

**Comment by mchalupa** [comment]
Works fine here (tried with fresh clone). Can you provide more information?

**Comment by rtrembecky** [comment]
Well, the build is aborted on line 261, saying there is no directory called LLVMSlicer. I fresh cloned symbiotic and I am building in other dir called symb-build - empty one. I don't know how "git submodule" works, but it is called in symbiotic main directory, so I can't see why should it create directories in build. From log it seems the clone runs, but i suppose it does so in symbiotic directory. Am I missing something here?

**Comment by rtrembecky** [comment]
Oh, am I supposed to build in main directory now? The wiki hasn't been changed, but I see that may be the only case here.

**Comment by mchalupa** [comment]
Oh, yes, you're right. I'll change the wiki and also fix the script so that the build will work in or out of the main directory. Thanks
