### ISSUE TITLE
documentation is buggy

### ISSUE THREAD

**Issue by vlstill** [staticafi/symbiotic#69]
> Then you can run symbiotic-build.sh script.
> 
> $ cd symbiotic
> $ ./symbiotic-build.sh make_options

there is ./build.sh but no `./symbiotic-build.sh`

> Running Symbiotic is very easy. Just give it a C program:
>
> $ ./symbiotic file.c

which one is that:

```
$ find -name symbiotic
./scripts/symbiotic
./install/lib/symbioticpy/symbiotic
./install/bin/symbiotic
./lib/symbioticpy/symbiotic
```

**Comment by mchalupa** [comment]
Thanks for the report, I fixed these. The documentation would need some improvement...
