### ISSUE TITLE
--bc option does not work

### ISSUE THREAD

**Issue by mchalupa** [staticafi/symbiotic#80]
$subj

**Comment by lzaoral** [comment]
Hi,
it seems, that `--bc` option still does not work even with the latest Symbiotic, at least when combined with `--prp=memsafety`. However, it may be quite useful for verifiaction of Autotools/CMake projects compiled using [`wllvm`](https://github.com/travitch/whole-program-llvm).

Sample code:
```c
int main(void)
{
    char arr[1];
    arr[1] = 0;
}
```

Problem:
```
$ clang -O0 -c -emit-llvm -o main.bc main.c
$ symbiotic --bc --prp=memsafety main.bc
7.0.0-dev-llvm-9.0.1-symbiotic:88057663-dg:e89761ff-sbt-slicer:fff6245c-sbt-instrumentation:2f9be629-klee:59f3e288
INFO: Starting instrumentation
wrapper: `which slllvm` failed with error code 1

Running DG points-to analysis with inv...
PTA inv done.
PredatorPlugin: Running Predator...
|> predator_wrapper.py --out predator.log --32 predator_in.bc
wrapper: `which slllvm` failed with error code 1
Predator wrapper finished with non-0 exit status
PredatorPlugin: failed to open file with predator output
RESULT: ERROR (Instrumenting the code failed)
ERROR:  == FAILURE ==
Instrumenting the code failed
```
Symbiotic finds the out-of-bounds array access if the .c is used directly.

**Comment by mchalupa** [comment]
The problem here is that `sbt-instr` segfaults for some reason.

**Comment by mchalupa** [comment]
The problem is that the input file has no debugging information, which was required by `sbt-instr`. Now it should work.

**Comment by lzaoral** [comment]
I have tested the fix and in works. Thanks!
