### ISSUE TITLE
include_next fails

### ISSUE THREAD

**Issue by xbauch** [staticafi/symbiotic#81]
Including the library "limits.h" causes symbiotic to fail.

xbauch@Rak:~/code/symbiotic$ ./install/bin/symbiotic ~/CS_C919_3/test.c 
5.0.0-symbiotic:5.0.0
cc: /usr/include/limits.h:123:16: fatal error: 'limits.h' file not found

RESULT: ERROR (Compiling source 'test.c' failed)
ERROR:  == FAILURE ==
Compiling source 'test.c' failed
xbauch@Rak:~/code/symbiotic$ cat ~/CS_C919_3/test.c 
#include <limits.h>
int main() {
  return 0;
}

**Comment by mchalupa** [comment]
As a temporary workaround, you can export CPPFLAGS variable or pass --cppflags=-I/path/to/limits.h

**Comment by xbauch** [comment]
xbauch@Rak:~/code/symbiotic$ ./install/bin/symbiotic --cppflags=-I/usr/include/limits.h ~/CS_C919_3/test.c 
5.0.0-symbiotic:5.0.0
cc: /usr/include/limits.h:123:16: fatal error: 'limits.h' file not found

RESULT: ERROR (Compiling source 'test.c' failed)
ERROR:  == FAILURE ==
Compiling source 'test.c' failed

It is not the include from the C file that causes the problem. It is the `include_next<limits.h>` from inside limits.h that Symbiotic cannot find.

**Comment by mchalupa** [comment]
Can you post here the output with `--debug=all` option?

**Comment by mchalupa** [comment]
Oh, one more thing. In CPPFLAGS you give just the directory, so instead of `--cppflags=-I/usr/include/limits.h` use `--cppflags=-I/usr/include/`. (Alternatively, I think you could use small `-i` to give directly the file).

**Comment by xbauch** [comment]
xbauch@Rak:~/code/symbiotic$ ./install/bin/symbiotic --debug=all --cppflags=-I/usr/include ~/CS_C919_3/test.c 
5.0.0-symbiotic:5.0.0
DBG: Symbiotic dir: /home/xbauch/code/symbiotic/install
DBG: PATH=/home/xbauch/code/symbiotic/install/llvm-3.9.1/bin:/home/xbauch/code/symbiotic/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
DBG: LD_LIBRARY_PATH=/home/xbauch/code/symbiotic/install/llvm-3.9.1/lib:/home/xbauch/code/symbiotic/install/lib
DBG: C_INCLUDE_DIR=/home/xbauch/code/symbiotic/install/llvm-3.9.1/include:/home/xbauch/code/symbiotic/install/include
DBG: Working directory: /tmp/symbiotic-H4NFum
DBG: Running Symbiotic with klee
DBG: 'clang' is '/home/xbauch/code/symbiotic/install/llvm-3.9.1/bin/clang'
|> clang -c -emit-llvm -include symbiotic.h -Wno-unused-parameter -Wno-unused-attribute -Wno-unused-label -Wno-unknown-pragmas -g -I/usr/include -I/home/xbauch/code/symbiotic/install/llvm-3.9.1/include -I/home/xbauch/code/symbiotic/install/include -o test.bc test.c
DBG: warning: unknown warning option '-Wno-unused-attribute'; did you mean '-Wno-ignored-attributes'? [-Wunknown-warning-option]
DBG: In file included from test.c:1:
cc: /usr/include/limits.h:123:16: fatal error: 'limits.h' file not found

DBG: # include_next <limits.h>
DBG:                ^
DBG: 1 warning and 1 error generated.
RESULT: ERROR (Compiling source 'test.c' failed)
ERROR:  == FAILURE ==
Compiling source 'test.c' failed

**Comment by mchalupa** [comment]
And if you try:
```
CPPFLAGS=-I/usr/include ./install/bin/symbiotic --debug=all  ~/CS_C919_3/test.c
```
It seems that we have  also the `--cppflags` option broken (we don't use it much). Will fix it.

**Comment by xbauch** [comment]
I think it is not in the `--cppflags` since the clang call contain the option. Anyway

xbauch@Rak:~/code/symbiotic$ CPPFLAGS=-I/usr/include ./install/bin/symbiotic --debug=all  ~/CS_C919_3/test.c
5.0.0-symbiotic:5.0.0
DBG: Symbiotic dir: /home/xbauch/code/symbiotic/install
DBG: PATH=/home/xbauch/code/symbiotic/install/llvm-3.9.1/bin:/home/xbauch/code/symbiotic/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
DBG: LD_LIBRARY_PATH=/home/xbauch/code/symbiotic/install/llvm-3.9.1/lib:/home/xbauch/code/symbiotic/install/lib
DBG: C_INCLUDE_DIR=/home/xbauch/code/symbiotic/install/llvm-3.9.1/include:/home/xbauch/code/symbiotic/install/include
DBG: CPPFLAGS="-I/usr/include"
DBG: Working directory: /tmp/symbiotic-CZTL_0
DBG: Running Symbiotic with klee
DBG: 'clang' is '/home/xbauch/code/symbiotic/install/llvm-3.9.1/bin/clang'
|> clang -c -emit-llvm -include symbiotic.h -Wno-unused-parameter -Wno-unused-attribute -Wno-unused-label -Wno-unknown-pragmas -g -I/home/xbauch/code/symbiotic/install/llvm-3.9.1/include -I/home/xbauch/code/symbiotic/install/include -I/usr/include -o test.bc test.c
DBG: warning: unknown warning option '-Wno-unused-attribute'; did you mean '-Wno-ignored-attributes'? [-Wunknown-warning-option]
DBG: In file included from test.c:1:
cc: /usr/include/limits.h:123:16: fatal error: 'limits.h' file not found

DBG: # include_next <limits.h>
DBG:                ^
DBG: 1 warning and 1 error generated.
RESULT: ERROR (Compiling source 'test.c' failed)
ERROR:  == FAILURE ==
Compiling source 'test.c' failed

**Comment by mchalupa** [comment]
Seems weird, it the file `limits.h` on the place?

**Comment by xbauch** [comment]
Yes, `limits.h` is in /usr/include. And on the line 123 there is `# include_next <limits.h>`. It is this second (recursive?) inclusion that symbiotic fails to find.

**Comment by mchalupa** [comment]
I see. So instead of `/usr/include` there should be another path used (https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html). Some path where the `limits.h` is but different from `/usr/include/`. I turned on searching include paths in Symbiotic (b627bfffe6651c5), so you can try pull the fixed version.

**Comment by xbauch** [comment]
Works now.
