### ISSUE TITLE
_Bool type unknown in .cpp files

### ISSUE THREAD

**Issue by xbauch** [staticafi/symbiotic#82]
xbauch@Rak:~/code/symbiotic$ ./install/bin/symbiotic --debug=all --cppflags=-I/home/xbauch/CS_C919_3 ~/CS_C919_3/test3.cpp 
5.0.0-symbiotic:5.0.0
DBG: Symbiotic dir: /home/xbauch/code/symbiotic/install
DBG: PATH=/home/xbauch/code/symbiotic/install/llvm-3.9.1/bin:/home/xbauch/code/symbiotic/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
DBG: LD_LIBRARY_PATH=/home/xbauch/code/symbiotic/install/llvm-3.9.1/lib:/home/xbauch/code/symbiotic/install/lib
DBG: C_INCLUDE_DIR=/home/xbauch/code/symbiotic/install/llvm-3.9.1/include:/home/xbauch/code/symbiotic/install/include
DBG: Working directory: /tmp/symbiotic-nrE_93
DBG: Running Symbiotic with klee
DBG: 'clang' is '/home/xbauch/code/symbiotic/install/llvm-3.9.1/bin/clang'
|> clang -c -emit-llvm -include symbiotic.h -Wno-unused-parameter -Wno-unused-attribute -Wno-unused-label -Wno-unknown-pragmas -g -I/home/xbauch/CS_C919_3 -I/home/xbauch/code/symbiotic/install/llvm-3.9.1/include -I/home/xbauch/code/symbiotic/install/include -o test3.bc test3.cpp
DBG: warning: unknown warning option '-Wno-unused-attribute'; did you mean '-Wno-ignored-attributes'? [-Wunknown-warning-option]
DBG: In file included from <built-in>:1:
cc: /home/xbauch/code/symbiotic/install/include/symbiotic.h:14:8: error: unknown type name '_Bool'

DBG: extern _Bool __VERIFIER_nondet__Bool(void);
DBG:        ^
DBG: 1 warning and 1 error generated.
RESULT: ERROR (Compiling source 'test3.cpp' failed)
ERROR:  == FAILURE ==
Compiling source 'test3.cpp' failed
xbauch@Rak:~/code/symbiotic$ cat ~/CS_C919_3/test3.cpp 
int main() {
  return __VERIFIER_nondet__Bool();
}

If I rename the input file to `test3.c` then the verification runs successfully.

**Comment by mchalupa** [comment]
Unfortunately, Symbiotic does not support C++.

**Comment by xbauch** [comment]
Fair enough.
