### ISSUE TITLE
docker pull command suggested in README.md does not work

### ISSUE THREAD

**Issue by kdudka** [staticafi/symbiotic#87]
The `docker pull` command suggested in `README.md` does not work:
```
$ docker pull mchalupa/symbiotic    
Using default tag: latest
Error response from daemon: manifest for mchalupa/symbiotic:latest not found
```

Either the `latest` tag should be created on Docker Hub, or `README.md` should suggest the following command instead:
```
$ docker pull mchalupa/symbiotic:dev
```

I am using the default configuration of `docker-18.03.1`.

**Comment by mchalupa** [comment]
Should be fixed now, thanks for the report.
