### ISSUE TITLE
symbiotic misses a double free when heap pointers are compared

### ISSUE THREAD

**Issue by kdudka** [staticafi/symbiotic#89]
`symbiotic --prp=memsafety` sees no errors in the following program despite it crashes on a double free:
```
#include <stdlib.h>
  
int main() {
    void *x = malloc(0x1000);
    free(x);
    void *y = malloc(0x1000);
    if (x == y)
        free(y);
    free(y);
}
```

**Comment by mchalupa** [comment]
This is an internal problem of KLEE. It does not consider that the pointers may be the same, as it uses the real addresses returned from `malloc`. These addresses are very likely to be different because KLEE allocates other memory internally between the two calls to `malloc` and thus the condition `x == y` is false.

**Comment by kdudka** [comment]
> it uses the real addresses returned from malloc

If it really does, the analysis is unsound by design.  And it can be even worse when pointers are compared for inequality: having a condition like `(x < y)` in a similar example where (`x` and `y` point at two distinct pieces of allocated memory) can even yield a qualitatively different result each time the analysis is run.

I think that KLEE should follow both the branches unless it is able to **prove** that exactly one of them is feasible in the given state.  Comparing some implementation-specific pointers of KLEE itself hardly classifies as proof.

**Comment by mchalupa** [comment]
Agree. We are trying to get rid of this stuff continuously (e.g. a few months ago Michael implemented support for symbolic-size allocations: https://github.com/msimacek/klee/tree/symbolic-memory), but it is a slow process.

**Comment by kdudka** [comment]
Symbiotic now supports multiple symbolic execution backends.  Are any of them able to properly verify the example in question?

**Comment by mchalupa** [comment]
Unfortunately, all backends that I tried (KLEE, DIVINE, CPAchecker, Seahorn, SMACK) are not able to find this error...

**Comment by kdudka** [comment]
OK, thanks for checking!  I can see that Divine already tracks this shortcoming:

https://divine.fi.muni.cz/trac/ticket/16

**Comment by lzaoral** [comment]
I know that there were some changes to KLEE in past few months to support symbolic allocations so I wanted to try it. But now @kdudka's example makes `symbiotic` crash.

```
symbiotic --prp=memsafety ptrs.c
8.0.0-pre-llvm-11.0.0-symbiotic:d52fe5c6-dg:c04e6dd4-sbt-slicer:319209dd-sbt-instrumentation:ad1d134f-klee:18262515
INFO: Looking for invalid dereferences, invalid free, memory leaks, etc.
INFO: Starting instrumentation
wrapper: `which slllvm` failed with error code 1

INFO: Instrumentation time: 0.055518150329589844
INFO: Optimizations time: 0.018459320068359375
INFO: Starting slicing
INFO: Total slicing time: 0.020775318145751953
INFO: Optimizations time: 0.017686843872070312
INFO: After-slicing optimizations and transformations time: 2.0265579223632812e-05
INFO: Starting verification
KLEE: WARNING: undefined reference to function: __symbiotic_keep_ptr
KLEE: WARNING ONCE: Alignment of memory from call "malloc" is not modelled. Using alignment of 8.
KLEE: output directory is "/tmp/symbiotic-6ejsisu6/klee-out-0"
KLEE: Using Z3 solver backend
KLEE: WARNING: undefined reference to function: __symbiotic_keep_ptr
KLEE: WARNING ONCE: Alignment of memory from call "malloc" is not modelled. Using alignment of 8.
 #0 0x00007fe201c5427a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/lib64/libLLVM-11.so+0xa8b27a)
 #1 0x00007fe201c524e4 llvm::sys::RunSignalHandlers() (/lib64/libLLVM-11.so+0xa894e4)
 #2 0x00007fe201c52676 (/lib64/libLLVM-11.so+0xa89676)
 #3 0x00007fe200e53a60 __restore_rt (/lib64/libc.so.6+0x3da60)
 #4 0x0000555dd13bb6b1 klee::MemoryObject::getSymbolicAddress(klee::ArrayCache&) (/opt/symbiotic/llvm-11.0.0/bin/klee+0x946b1)
 #5 0x0000555dd139f8f1 klee::Executor::executeInstruction(klee::ExecutionState&, klee::KInstruction*) (/opt/symbiotic/llvm-11.0.0/bin/klee+0x788f1)
 #6 0x0000555dd13a45f5 klee::Executor::run(klee::ExecutionState&) (/opt/symbiotic/llvm-11.0.0/bin/klee+0x7d5f5)
 #7 0x0000555dd13af713 klee::Executor::runFunctionAsMain(llvm::Function*, int, char**, char**) (/opt/symbiotic/llvm-11.0.0/bin/klee+0x88713)
 #8 0x0000555dd137522e main (/opt/symbiotic/llvm-11.0.0/bin/klee+0x4e22e)
 #9 0x00007fe200e3e1e2 __libc_start_main (/lib64/libc.so.6+0x281e2)
#10 0x0000555dd137ffde _start (/opt/symbiotic/llvm-11.0.0/bin/klee+0x58fde)
klee answered ERROR
INFO: Verification time: 0.32912158966064453
Failure!
NOTE: In the future, the result is going to be reported in SV-COMP format only with --report=sv-comp switch
RESULT: ERROR
INFO: Total time elapsed: 2.1768088340759277
```

**Comment by mchalupa** [comment]
The crash and actually the whole issue should be fixed now. Could you confirm?

**Comment by lzaoral** [comment]
Yes, it works for me as well. Thanks!
