### ISSUE TITLE
Symbiotic prepare phase fails when sigaction is used

### ISSUE THREAD

**Issue by dkozovsk** [staticafi/symbiotic#95]
This code gives ERROR (Prepare phase failed),
but when signal is used instead of sigaction it works fine.

    #include <stdio.h>
    #include <stdlib.h>
    #include <signal.h>
    #include <unistd.h> 
    void handler(int);

    int main (void)
    {
        struct sigaction sa={
            .sa_handler=handler
        };
        sigaction(SIGTERM, &sa, NULL);
        return 0;
    }

    void handler(int signum)
    {
        kill(SIGKILL,0);
    }

Tested with release symbiotic-5.0.1

**Comment by mchalupa** [comment]
I can reproduce the crash, thanks. By the way, symbiotic does not support any asynchronous actions (like signals) as KLEE does not support them, so it may miss bugs in code that uses them.

**Comment by mchalupa** [comment]
The crash should be fixed by the latest commit. However, the inability to work with signals cannot be fixed that easily.
